name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey You might''ve done somthing weird right there mate, check it out and try again'
        pr-message: 'Heyo Use my knowledge wisely young''un'
